// examples/svelte/StreamVizWidget.svelte
<script lang="ts">
  /**
   * StreamViz Widget Component for Svelte 5
   *
   * Embeds a real-time StreamViz widget via iframe.
   *
   * @example
   * ```svelte
   * <StreamVizWidget widgetId="revenue" class="h-32 w-full" />
   * ```
   */

  interface Props {
    widgetId: string;
    serverUrl?: string;
    class?: string;
  }

  let { widgetId, serverUrl = "http://localhost:3000", class: className = "" }: Props = $props();

  function handleError() {
    console.warn(`StreamViz widget "${widgetId}" failed to load`);
  }
</script>

<iframe
  src="{serverUrl}/embed/{widgetId}"
  class={className}
  title="StreamViz {widgetId}"
  on:error={handleError}
></iframe>

<style>
  iframe {
    border: none;
    width: 100%;
    height: 100%;
  }
</style>

// examples/nextjs/StreamVizWidget.tsx
"use client";

import { useEffect, useRef } from "react";

interface StreamVizWidgetProps {
  widgetId: string;
  serverUrl?: string;
  className?: string;
  style?: React.CSSProperties;
}

/**
 * StreamViz Widget Component for Next.js
 *
 * Embeds a real-time StreamViz widget via iframe.
 *
 * @example
 * ```tsx
 * <StreamVizWidget widgetId="revenue" className="h-32 w-full" />
 * ```
 */
export function StreamVizWidget({
  widgetId,
  serverUrl = "http://localhost:3000",
  className = "",
  style,
}: StreamVizWidgetProps) {
  const iframeRef = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    // Handle iframe load errors gracefully
    const iframe = iframeRef.current;
    if (!iframe) return;

    const handleError = () => {
      console.warn(`StreamViz widget "${widgetId}" failed to load`);
    };

    iframe.addEventListener("error", handleError);
    return () => iframe.removeEventListener("error", handleError);
  }, [widgetId]);

  return (
    <iframe
      ref={iframeRef}
      src={`${serverUrl}/embed/${widgetId}`}
      className={className}
      style={{
        border: "none",
        width: "100%",
        height: "100%",
        ...style,
      }}
      title={`StreamViz ${widgetId}`}
    />
  );
}
